language: ruby
cache: bundler
bundler_args: '--without production development'
rvm:
  - 2.2.2
script:
  - bundle exec rake test
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
