language: ruby
rvm:
- 2.2.2
env:
  global:
    secure: tqdOpBB/BlVboluH8inIuAXCcz+w29Kus/Rk94JczSIpRk4dpYgdzhnn97hNAdN7sAMdH8UYzQ0L5y+LF9ng5Zh/FIMhx99LYVv2KM4FidChwAd8Hepesb7GKy8h3Cp6HNVAKnLgly0iV5klEdkkB30x8ihH8xHCcD994huQk20y1MPkA7m7XvmM+YU4XUJD91bEmFN07LYPHpx2pJQYUIuOWugYY/qAoDqqcnO4/o3l+G6lLlvcQ7uNf8IY0PRfeVnrh0/+HlolkqAlkTEQGTKt9QmomgiGKvevCefbD++Zrqc+yNI9POGBouFaPBnMQgT1HDP7YmAz84LGAmAKkBtNI0obPlg2wKdHuKqHqjiSrZlNoFNHhx7VNWEderjOOCO0wK3bvRjujA/1AHE8DNHxCAx2NUUk8sZb3AyP/0racvj48vQJw28CRqWMBrPMh/ZrIa4rXIf2IU1mXRmjkIidOEkbN71pXMfa7ghMpACavcQSrrEOk1H5gDC500lFRwJ87gQPAH/s1a0EAHd76MOYyqOE/VOOX6VP16QzgiGJa+2XAkzsCtscVz+VNDXpZt5qW++INo6VT0+kI5/1nq9YPcyHfshPw/pzq84CXaadgkx1DS2WRZqg8ax0HmUyaZb1wy9fFGPl4NSTurBoK+yeMQY3zG6Aqov+oRRHGi0=
